// Generated by typings
// Source: wwwroot/jspm_packages/github/sketch7/ssv-au-core@route-builder/typings/logging/logger.srv.d.ts
declare module '~ssv-au-core/logging/logger.srv' {
export class LogService {
    getLogger(sourceId: string): ILog;
}
export class Log implements ILog {
    private logger;
    constructor(logger: any);
    debug(method: string, message?: string, data?: any): void;
    info(method: string, message?: string, data?: any): void;
    warn(method: string, message?: string, data?: any): void;
    error(method: string, message?: string, data?: any): void;
    private log(type, method, message?, data?);
    private buildLogMessage(method, message?);
}
export interface ILog {
    debug(method: string, message?: string, data?: any): void;
    info(method: string, message?: string, data?: any): void;
    warn(method: string, message?: string, data?: any): void;
    error(method: string, message?: string, data?: any): void;
}
}
declare module 'ssv-au-core/logging/logger.srv' {
import alias = require('~ssv-au-core/logging/logger.srv');
export = alias;
}

// Generated by typings
// Source: wwwroot/jspm_packages/github/sketch7/ssv-au-core@route-builder/typings/logging/logging.d.ts
declare module '~ssv-au-core/logging/logging' {
export * from '~ssv-au-core/logging/logger.srv';
}
declare module 'ssv-au-core/logging/logging' {
import alias = require('~ssv-au-core/logging/logging');
export = alias;
}

// Generated by typings
// Source: wwwroot/jspm_packages/github/sketch7/ssv-au-core@route-builder/typings/routing/route-builder.srv.d.ts
declare module '~ssv-au-core/routing/route-builder.srv' {
import { RouteConfig } from 'aurelia-router';
import { LogService } from '~ssv-au-core/logging/logging';
export class RouteBuilder {
    private logger;
    private routes;
    constructor(logService: LogService);
    map(routes: Route[]): void;
    get(key: string): Route;
    generateUrl(key: string, data?: any): string;
    verify(): void;
    private verifyParent(route);
    private validate(route);
    private buildRoutePath(menuItem, routePath, data?);
    private extractParentKey(route);
}
export interface Route {
    key: string;
    model: RouteConfig;
    parentKey?: string;
}
export interface RouteParams {
    key: string;
    value: string;
}
}
declare module 'ssv-au-core/routing/route-builder.srv' {
import alias = require('~ssv-au-core/routing/route-builder.srv');
export = alias;
}

// Generated by typings
// Source: wwwroot/jspm_packages/github/sketch7/ssv-au-core@route-builder/typings/routing/routing.d.ts
declare module '~ssv-au-core/routing/routing' {
export * from '~ssv-au-core/routing/route-builder.srv';
}
declare module 'ssv-au-core/routing/routing' {
import alias = require('~ssv-au-core/routing/routing');
export = alias;
}

// Generated by typings
// Source: wwwroot/jspm_packages/github/sketch7/ssv-au-core@route-builder/typings/index.d.ts
declare module 'ssv-au-core' {
export * from '~ssv-au-core/logging/logging';
export * from '~ssv-au-core/routing/routing';
}
