// Generated by typings
// Source: wwwroot/jspm_packages/github/sketch7/ssv-au-core@develop/typings/logging/logger.svc.d.ts
declare module '~ssv-au-core/logging/logger.svc' {
export class LogService {
    getLogger(sourceId: string): ILog;
}
export class Log implements ILog {
    private logger;
    constructor(logger: any);
    debug(method: string, message?: string, data?: any): void;
    info(method: string, message?: string, data?: any): void;
    warn(method: string, message?: string, data?: any): void;
    error(method: string, message?: string, data?: any): void;
    private log(type, method, message?, data?);
    private buildLogMessage(method, message?);
}
export interface ILog {
    debug(method: string, message?: string, data?: any): void;
    info(method: string, message?: string, data?: any): void;
    warn(method: string, message?: string, data?: any): void;
    error(method: string, message?: string, data?: any): void;
}
}
declare module 'ssv-au-core/logging/logger.svc' {
import alias = require('~ssv-au-core/logging/logger.svc');
export = alias;
}

// Generated by typings
// Source: wwwroot/jspm_packages/github/sketch7/ssv-au-core@develop/typings/logging/logging.d.ts
declare module '~ssv-au-core/logging/logging' {
export * from '~ssv-au-core/logging/logger.svc';
}
declare module 'ssv-au-core/logging/logging' {
import alias = require('~ssv-au-core/logging/logging');
export = alias;
}

// Generated by typings
// Source: wwwroot/jspm_packages/github/sketch7/ssv-au-core@develop/typings/index.d.ts
declare module 'ssv-au-core' {
export * from '~ssv-au-core/logging/logging';
}
